### PR TITLE
Revisions to v2 api

### PR DESCRIPTION
**Pull request by J-Ogden99**

### CODE REVIEW

**Review by rileyhales — APPROVED** [review]

**Comment by rileyhales** [comment]
- Updates documentation
- moves return_format to a path parameter, not a query parameter in REST pattern
- adds shorthand names for several products recognized by URL patterns
- fix bug in retrieving historical averages
- adds hydroviewer product which returns records, stats, and return periods all in 1 json for easier fetch/plot
- improves analytics to use shorthand names, include return format

**Comment by rileyhales** [comment]
Also rounds all discharge data to 2 decimals rather than the 10-15 it currently is

**Comment by rileyhales** [comment]
@msouff 

This pull request has updated docs, various bug fixes, and reimplements logging in the api container. Its ready to be merged. When you're ready to deploy it, i'd like to be there with you to go through the deploy steps and record it so i can practice.

**Comment by rileyhales** [comment]
removes AvailableRegions
AvailableDates does not require a reachid/region anymore
ForecastWarnings does not require a region and instead has a column indicating which region the warning applies to

**Review by msouff — APPROVED** [review]

**Pull request merged**
